services:
  # Backend Service
  - type: web
    name: future-blink-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm run dev"
    envVars:
      - key: PORT
        value: 3000
      - key: MONGODB_URL
        fromSecret: mongodb_url
      - key: JWT_SECRET
        fromSecret: jwt_secret
      - key: NODE_ENV
        value: production
